# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [175]:
# Your code here
import pandas as pd

In [176]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df= pd.read_csv(url)

print(df.head())

  Customer          ST GENDER             Education Customer Lifetime Value  \
0  RB50392  Washington    NaN                Master                     NaN
1  QZ44356     Arizona      F              Bachelor              697953.59%
2  AI49188      Nevada      F              Bachelor             1288743.17%
3  WW63253  California      M              Bachelor              764586.18%
4  GA49547  Washington      M  High School or Below              536307.65%

    Income  Monthly Premium Auto Number of Open Complaints     Policy Type  \
0      0.0                1000.0                    1/0/00   Personal Auto
1      0.0                  94.0                    1/0/00   Personal Auto
2  48767.0                 108.0                    1/0/00   Personal Auto
3      0.0                 106.0                    1/0/00  Corporate Auto
4  36357.0                  68.0                    1/0/00   Personal Auto

   Vehicle Class  Total Claim Amount
0  Four-Door Car            2.704934
1  Four-Door Car         1131.464935
2   Two-Door Car          566.472247
3            SUV          529.881344
4  Four-Door Car           17.269323

In [177]:
df.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')

In [178]:
df.columns = df.columns.str.lower()

In [179]:
df.columns = df.columns.str.replace(" ", "_")

In [180]:
df = df.rename(columns ={'st':"state"})

In [181]:
df.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='object')

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [182]:
df.gender.value_counts()

gender
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64

In [183]:
# Your code here
df['gender'] =  df['gender'].replace({'female': 'F', 'Femal': 'F', 'f': 'F', 'Male': 'M', 'm': 'M'})
df['gender'].value_counts()

gender
F    502
M    452
Name: count, dtype: int64

In [184]:
state_mapping = { 
    "Arizona":"AZ",
    "California":"Cali",
    "California":"CA",
    "Washington":"WA",
    "Nevada": "NV",
    "Oregon": "OG"}
df['state'] = df['state'].replace(state_mapping)

In [185]:
df['state'].unique()

array(['WA', 'AZ', 'NV', 'CA', 'OG', 'Cali', nan], dtype=object)

In [186]:
df['education'] = df['education'].replace({
    'Bachelors': 'Bachelor'})

In [187]:
df['customer_lifetime_value'] = df['customer_lifetime_value'].str.replace('%', '')

In [188]:
df["vehicle_class"].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury SUV', 'Sports Car',
       'Luxury Car', nan], dtype=object)

In [189]:
df['vehicle_class'].value_counts()

vehicle_class
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: count, dtype: int64

In [190]:
df["vehicle_class"] = df["vehicle_class"].replace(
    {
    "Sports Car" : "Luxury",
    "Luxury SUV": "Luxury",
    "Luxury Car": "Luxury"})

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [191]:
print(df["customer_lifetime_value"].dtypes)

object

In [192]:
df["customer_lifetime_value"] = df["customer_lifetime_value"].astype(float)

In [193]:
df["customer_lifetime_value"].head()

0           NaN
1     697953.59
2    1288743.17
3     764586.18
4     536307.65
Name: customer_lifetime_value, dtype: float64

In [194]:
df['number_of_open_complaints'].unique()

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan],
      dtype=object)

In [195]:
df['number_of_open_complaintes'] = df['number_of_open_complaints'].str.split('/')

In [196]:
df['number_of_open_complaints'].unique()

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan],
      dtype=object)

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [197]:
df.isnull().sum()

customer                      2937
state                         2937
gender                        3054
education                     2937
customer_lifetime_value       2940
income                        2937
monthly_premium_auto          2937
number_of_open_complaints     2937
policy_type                   2937
vehicle_class                 2937
total_claim_amount            2937
number_of_open_complaintes    2937
dtype: int64

In [198]:
df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,number_of_open_complaintes
0,RB50392,WA,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934,"[1, 0, 00]"
1,QZ44356,AZ,F,Bachelor,697953.59,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935,"[1, 0, 00]"
2,AI49188,NV,F,Bachelor,1288743.17,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247,"[1, 0, 00]"
3,WW63253,CA,M,Bachelor,764586.18,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344,"[1, 0, 00]"
4,GA49547,WA,M,High School or Below,536307.65,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323,"[1, 0, 00]"

In [199]:
drop_col = ['customer', 'state', 'education','income','number_of_open_complaints','policy_type','vehicle_class','total_claim_amount','number_of_open_complaintes']

In [200]:
df = df.dropna(subset=drop_col)

In [201]:
df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,number_of_open_complaintes
0,RB50392,WA,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934,"[1, 0, 00]"
1,QZ44356,AZ,F,Bachelor,697953.59,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935,"[1, 0, 00]"
2,AI49188,NV,F,Bachelor,1288743.17,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247,"[1, 0, 00]"
3,WW63253,CA,M,Bachelor,764586.18,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344,"[1, 0, 00]"
4,GA49547,WA,M,High School or Below,536307.65,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323,"[1, 0, 00]"

In [202]:
df['gender'].fillna(method='ffill').tail()

/var/folders/9l/kk5xty3s5gn6t443byvnr8040000gn/T/ipykernel_25690/3785345695.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['gender'].fillna(method='ffill').tail()

1066    M
1067    F
1068    F
1069    F
1070    F
Name: gender, dtype: object

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [203]:
df.head(5)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,number_of_open_complaintes
0,RB50392,WA,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934,"[1, 0, 00]"
1,QZ44356,AZ,F,Bachelor,697953.59,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935,"[1, 0, 00]"
2,AI49188,NV,F,Bachelor,1288743.17,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247,"[1, 0, 00]"
3,WW63253,CA,M,Bachelor,764586.18,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344,"[1, 0, 00]"
4,GA49547,WA,M,High School or Below,536307.65,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323,"[1, 0, 00]"

In [204]:
df_str = df.astype(str)
df_str.duplicated().any()

np.False_

In [205]:
df_str.drop_duplicates(inplace=True)

In [206]:
df_str.duplicated().sum()

np.int64(0)

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [211]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df= pd.read_csv(url)

print(df.head())

  Customer          ST GENDER             Education Customer Lifetime Value  \
0  RB50392  Washington    NaN                Master                     NaN
1  QZ44356     Arizona      F              Bachelor              697953.59%
2  AI49188      Nevada      F              Bachelor             1288743.17%
3  WW63253  California      M              Bachelor              764586.18%
4  GA49547  Washington      M  High School or Below              536307.65%

    Income  Monthly Premium Auto Number of Open Complaints     Policy Type  \
0      0.0                1000.0                    1/0/00   Personal Auto
1      0.0                  94.0                    1/0/00   Personal Auto
2  48767.0                 108.0                    1/0/00   Personal Auto
3      0.0                 106.0                    1/0/00  Corporate Auto
4  36357.0                  68.0                    1/0/00   Personal Auto

   Vehicle Class  Total Claim Amount
0  Four-Door Car            2.704934
1  Four-Door Car         1131.464935
2   Two-Door Car          566.472247
3            SUV          529.881344
4  Four-Door Car           17.269323

In [212]:
import Lab_functions as fc

In [213]:
df = fc.clean_column_names(df)
df = fc.clean_invalid_values(df)
df = fc.format_data_types(df)
df = fc.handle_null_values(df)
df = fc.remove_duplicates(df)

/Users/hanane/Ironhack/lab-dw-data-cleaning-and-formatting/Lab_functions.py:88: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["gender"] = df["gender"].fillna(method="ffill")
/Users/hanane/Ironhack/lab-dw-data-cleaning-and-formatting/Lab_functions.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["gender"] = df["gender"].fillna(method="ffill")

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [215]:
df[['total_claim_amount','customer_lifetime_value']].describe()

       total_claim_amount  customer_lifetime_value
count         1071.000000             1.068000e+03
mean           404.986909             7.936903e+05
std            293.027260             6.434784e+05
min              0.382107             2.004351e+05
25%            202.157702             4.034080e+05
50%            354.729129             5.881742e+05
75%            532.800000             8.962872e+05
max           2893.239678             5.816655e+06

In [216]:
claim_75 = df['total_claim_amount'].quantile(0.75)
clv_25 = df['customer_lifetime_value'].quantile(0.25)

In [219]:
high_claim = df[
    (df['total_claim_amount'] > claim_75) &
    (df['customer_lifetime_value'] < clv_25)]

In [220]:

high_claim[['total_claim_amount','customer_lifetime_value']].describe()

       total_claim_amount  customer_lifetime_value
count           40.000000                40.000000
mean           723.776577            341577.910000
std            149.280606             56921.472027
min            537.600000            228759.690000
25%            633.378846            304220.875000
50%            685.284189            365995.370000
75%            799.200000            387364.700000
max           1185.988301            402381.440000